name: CI/CD Pipeline

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '14'

      - name: Install dependencies
        run: npm install
      
      - name: Run application
        run: nohup npm start & sleep 10
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test, build] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t hrishi0304/github-act-node-1:v1 .

      - name: Push Docker image
        run: docker push hrishi0304/github-act-node-1:v1
  