name: Reusable Test Workflow

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16, 18, 20] 

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }} 
          cache: 'npm' 
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Run tests
        run: npm test

      - name: Save test logs
        if: failure()
        run: cat npm-debug.log > test-log.txt || echo "No debug log found"

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.node-version }}
          path: test-log.txt
